### ISSUE TITLE
what's the excat rate limit for eNom API

### ISSUE THREAD

**Issue by jnozsc** [rightside-co/DeveloperSupport#1]
Hi

I am working on eNom API stuff.

since the Max result of each request is 100. I have to use a loop to iterate through all my domains.

if I run the for loop without a sleep function, it will raise a timeout error from eNom.

So I guess there may be an undocumented rate limit for API request.

Could I get the exact number on how frequently I can call the API? 

thanks

**Comment by sottey** [comment]
There isn't, technically, a limit on the API... The limiting is at the registry interaction level. The limit varies depending on the registry and systems involved. Many are at 60 requests per second but some are as low as 30 requests per minute. As you can see this is a wide spectrum.

Which TLD's were you targeting? I may be able to get you a more specific answer if I know which registries' domain extensions you are targeting.

Thanks!
Sean

**Comment by jnozsc** [comment]
my domains cross TLDs on

'mortgage', 'degree', 'xyz', 'sale', 'haus', 'us', 'rocks', 'rehab', 'live', 'ninja', 'com', 'market'

**Comment by sottey** [comment]
Ok. Most of these are going to limit less. If you want to email me your account name I can look at what is going on for you.

Thanks!
Sean (sean DOT ottey AT rightside.co)

**Comment by jnozsc** [comment]
ok, will send email
